#spring.application.name=Server-Registory
#server.port=8763
#
##this line stop self registration
#eureka.client.register-with-eureka=false
spring.application.name=Server-Registory

server.port=8763

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false